//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yara.Blog.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class author
    {
        public author()
        {
            this.contactUs = new HashSet<contactU>();
            this.posts = new HashSet<post>();
        }
    
        public int authorID { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public System.DateTime enrollmentDate { get; set; }
    
        public virtual ICollection<contactU> contactUs { get; set; }
        public virtual ICollection<post> posts { get; set; }
    }
}
