//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yara.Blog.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public int commentID { get; set; }
        public string Title { get; set; }
        public string Text { get; set; }
        public System.DateTime Created { get; set; }
        public int postID { get; set; }
    
        public virtual post post { get; set; }
    }
}
